#!/bin/bash
cd /opt 
sudo yum install java-1.8.0-openjdk-devel -y
sudo yum install git wget -y
sudo wget https://httpd-mirror.sergal.org/apache/tomcat/tomcat-9/v9.0.45/bin/apache-tomcat-9.0.45.tar.gz
sudo tar -xvf apache-tomcat-9.0.45.tar.gz
sudo rm apache-tomcat-9.0.45.tar.gz
sudo mv apache-tomcat-9.0.45 tomcat9
sudo chmod 777 -R /opt/tomcat9
sudo sh /opt/tomcat9/bin/startup.sh
 
      Springapp:


Install Docker on AWS Ubuntu
############################
#!/bin/bash
sudo apt update -y
sudo apt install docker.io -y
sudo usermod -aG docker ubuntu
sudo docker network create -d bridge mynw
sudo docker run -d -p 8080:8080 --name springapp  -e MONGO_DB_HOSTNAME=mongo -e MONGO_DB_USERNAME=devdb -e MONGO_DB_PASSWORD=devdb1234 --network mynw  mylandmarktech/spring-boot-mongo 

docker run -d --name mongo -e MONGO_INITDB_ROOT_USERNAME=devdb -e MONGO_INITDB_ROOT_PASSWORD=devdb1234  --network mynw mongo



nohup 
java -jar spring-boot-mongo-1.0.jar  to start the applicaion . 
&



 scp -i k23a.pem java-web-app.war ec2-user@3.18.107.160:/opt/tomcat9/webapps/

scp -i k23.pem java-web-app.war ec2-user@18.216.204.62:/opt/tomcat9/webapps/

scp -i k23.pem maven-web-app.war ec2-user@3.16.216.167:/opt/tomcat9/webapps/

 scp -i k23a.pem spring-boot-mongo-1.0.jar ec2-user@3.16.56.126:/opt/
